Repository brain-tec/reporting-engine, pull requests merged in 2022-06, with the labels that each got.

#391 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_py3o/__manifest__.py
  report_qweb_pdf_watermark/__manifest__.py
  report_xlsx/__manifest__.py
  report_xml/__manifest__.py
  requirements.txt
Labels: 14.0

#392 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  base_comment_template/__manifest__.py
  base_comment_template/wizard/base_comment_template_preview.py
Labels: 14.0

#393 Syncing from upstream OCA/reporting-engine (15.0)
  bi_sql_editor/i18n/ca.po
  report_qr/i18n/ca.po
  report_qweb_parameter/i18n/ca.po
  report_wkhtmltopdf_param/i18n/ca.po
  report_xlsx_helper/i18n/ca.po
  report_xml/i18n/ca.po
  sql_export/i18n/ca.po
  sql_export_excel/i18n/ca.po
  sql_request_abstract/i18n/ca.po
Labels: 15.0

#394 Backmerging 15.0 into 15.0.project_MI_465
  bi_sql_editor/i18n/ca.po
  report_qr/i18n/ca.po
  report_qweb_parameter/i18n/ca.po
  report_wkhtmltopdf_param/i18n/ca.po
  report_xlsx_helper/i18n/ca.po
  report_xml/i18n/ca.po
  sql_export/i18n/ca.po
  sql_export_excel/i18n/ca.po
  sql_request_abstract/i18n/ca.po
Labels: 15.0.project_mi_465

#395 [t127490][15.0][MIG] Migration of module report_qweb_element_page_visibility
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.rst
  report_qweb_element_page_visibility/readme/DESCRIPTION.rst
  report_qweb_element_page_visibility/readme/USAGE.rst
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 15.0.project_sv_559
