Repository brain-tec/reporting-engine, pull requests merged in 2022-12, with the labels that each got.

#433 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  bi_sql_editor/__manifest__.py
  bi_sql_editor/models/bi_sql_view.py
Labels: 14.0

#439 Syncing from upstream OCA/reporting-engine (16.0)
  sql_export/i18n/es_AR.po
Labels: 16.0

#440 Syncing from upstream OCA/reporting-engine (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  report_xml/i18n/en.po
Labels: 14.0

#441 Syncing from upstream OCA/reporting-engine (15.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  report_xml/i18n/en.po
Labels: 15.0

#442 Syncing from upstream OCA/reporting-engine (16.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  report_xml/i18n/en.po
Labels: 16.0

#443 Backmerge into project's branch
  .copier-answers.yml
  .pre-commit-config.yaml
  report_xml/i18n/en.po
Labels: 15.0.project_sy_639

#444 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
Labels: 16.0

#445 Syncing from upstream OCA/reporting-engine (15.0)
  report_wkhtmltopdf_param/i18n/es_AR.po
  report_xml/i18n/es_AR.po
Labels: 15.0

#446 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.rst
  report_qweb_element_page_visibility/readme/CREDITS.rst
  report_qweb_element_page_visibility/readme/DESCRIPTION.rst
  report_qweb_element_page_visibility/readme/USAGE.rst
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qweb_element_page_visibility/odoo/addons/report_qweb_element_page_visibility
  setup/report_qweb_element_page_visibility/setup.py
Labels: 15.0

#447 Syncing from upstream OCA/reporting-engine (15.0)
  sql_request_abstract/i18n/es_AR.po
Labels: 15.0

#448 Syncing from upstream OCA/reporting-engine (16.0)
  sql_export/i18n/it.po
  sql_request_abstract/i18n/it.po
Labels: 16.0

#449 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/__init__.py
  report_qweb_pdf_watermark/__manifest__.py
  report_qweb_pdf_watermark/demo/report.xml
  report_qweb_pdf_watermark/i18n/ca.po
  report_qweb_pdf_watermark/i18n/da.po
  report_qweb_pdf_watermark/i18n/de.po
  report_qweb_pdf_watermark/i18n/el_GR.po
  report_qweb_pdf_watermark/i18n/es.po
  report_qweb_pdf_watermark/i18n/es_CO.po
  report_qweb_pdf_watermark/i18n/fr.po
  report_qweb_pdf_watermark/i18n/gl.po
  report_qweb_pdf_watermark/i18n/hr.po
  report_qweb_pdf_watermark/i18n/hr_HR.po
  report_qweb_pdf_watermark/i18n/it.po
  report_qweb_pdf_watermark/i18n/nb_NO.po
  report_qweb_pdf_watermark/i18n/nl_NL.po
  report_qweb_pdf_watermark/i18n/pl.po
  report_qweb_pdf_watermark/i18n/pt.po
  report_qweb_pdf_watermark/i18n/pt_BR.po
  report_qweb_pdf_watermark/i18n/pt_PT.po
  report_qweb_pdf_watermark/i18n/report_qweb_pdf_watermark.pot
  report_qweb_pdf_watermark/i18n/sl.po
  report_qweb_pdf_watermark/i18n/tr.po
  report_qweb_pdf_watermark/i18n/tr_TR.po
  report_qweb_pdf_watermark/models/__init__.py
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/models/res_company.py
  report_qweb_pdf_watermark/readme/CONTRIBUTORS.rst
  report_qweb_pdf_watermark/readme/DESCRIPTION.rst
  report_qweb_pdf_watermark/readme/HISTORY.rst
  report_qweb_pdf_watermark/readme/INSTALL.rst
  report_qweb_pdf_watermark/readme/ROADMAP.rst
  report_qweb_pdf_watermark/readme/USAGE.rst
  report_qweb_pdf_watermark/static/description/icon.png
  report_qweb_pdf_watermark/static/description/index.html
  report_qweb_pdf_watermark/static/src/css/report_qweb_pdf_watermark.css
  report_qweb_pdf_watermark/tests/__init__.py
  report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
  report_qweb_pdf_watermark/views/ir_actions_report_xml.xml
  report_qweb_pdf_watermark/views/res_company.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qweb_pdf_watermark/odoo/addons/report_qweb_pdf_watermark
  setup/report_qweb_pdf_watermark/setup.py
Labels: 15.0
