Repository brain-tec/reporting-engine, pull requests merged in 2022-09, with the labels that each got.

#404 Syncing from upstream OCA/reporting-engine (13.0)
  bi_sql_editor/i18n/ca.po
  bi_sql_editor/i18n/es.po
Labels: 13.0

#405 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/report/report_abstract_xlsx.py
  report_xlsx/tests/test_report.py
Labels: 13.0

#407 [t128733] Update 15.0.project_SY_639 with latest 15.0
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
Labels: 15.0.project_sy_639

#408 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/report/report_abstract_xlsx.py
  report_xlsx/tests/test_report.py
Labels: 14.0

#409 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/report/report_abstract_xlsx.py
  report_xlsx/tests/test_report.py
Labels: 15.0

#412 Syncing from upstream OCA/reporting-engine (13.0)
  bi_sql_editor/i18n/ca.po
  bi_sql_editor/i18n/es.po
Labels: 13.0

#413 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_label/README.rst
  report_label/__init__.py
  report_label/__manifest__.py
  report_label/data/paperformat_label.xml
  report_label/demo/demo.xml
  report_label/i18n/report_label.pot
  report_label/models/__init__.py
  report_label/models/ir_actions_report.py
  report_label/models/ir_actions_server.py
  report_label/models/report_paperformat_label.py
  report_label/readme/CONFIGURE.rst
  report_label/readme/CONTRIBUTORS.rst
  report_label/readme/DESCRIPTION.rst
  report_label/readme/ROADMAP.rst
  report_label/readme/USAGE.rst
  report_label/reports/report_label.xml
  report_label/security/ir.model.access.csv
  report_label/static/description/configure_paperformat.png
  report_label/static/description/configure_report_label.png
  report_label/static/description/icon.png
  report_label/static/description/index.html
  report_label/static/description/label_wizard.png
  report_label/tests/__init__.py
  report_label/tests/test_report_label.py
  report_label/views/ir_actions_server.xml
  report_label/views/report_paperformat_label.xml
  report_label/wizards/__init__.py
  report_label/wizards/report_label_wizard.py
  report_label/wizards/report_label_wizard.xml
  report_py3o/controllers/main.py
  report_qweb_encrypt/controllers/main.py
  report_qweb_encrypt/models/ir_actions_report.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_label/odoo/addons/report_label
  setup/report_label/setup.py
Labels: 14.0
