Repository brain-tec/reporting-engine, pull requests merged in 2022-04, with the labels that each got.

#365 Syncing from upstream OCA/reporting-engine (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
Labels: 13.0

#366 Syncing from upstream OCA/reporting-engine (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  report_xlsx_helper/report/report_xlsx_abstract.py
Labels: 14.0

#367 Syncing from upstream OCA/reporting-engine (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0

#363 [bt#18235] fix watermark for QR bills (and ISR)
  report_qweb_pdf_watermark/models/ir_actions_report.py
Labels: 11.0.project_pr_449

#368 [t128608] add OCA/reporting-engine/pull/569
  .t2d.yml
  report_py3o/README.rst
  report_py3o/__manifest__.py
  report_py3o/controllers/main.py
  report_py3o/models/ir_actions_report.py
  report_py3o/readme/CONTRIBUTORS.rst
  report_py3o/static/description/index.html
  report_py3o/tests/test_report_py3o.py
  report_py3o/views/py3o_template.xml
  report_qr/static/src/js/py3oactionservice.esm.js
  requirements.txt
  setup/report_py3o/odoo/addons/report_py3o
  setup/report_py3o/setup.py
Labels: 15.0.project_sy_639

#369 [t128608] add ir.model.access.csv
  report_py3o/security/ir.model.access.csv
Labels: 15.0.project_sy_639

#371 Syncing from upstream OCA/reporting-engine (13.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
Labels: 13.0

#373 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  oca_dependencies.txt
  report_async/README.rst
  report_async/__init__.py
  report_async/__manifest__.py
  report_async/data/mail_template.xml
  report_async/demo/report_async_demo.xml
  report_async/i18n/report_async.pot
  report_async/models/__init__.py
  report_async/models/ir_report.py
  report_async/models/report_async.py
  report_async/readme/CONTRIBUTORS.rst
  report_async/readme/DESCRIPTION.rst
  report_async/readme/USAGE.rst
  report_async/security/ir.model.access.csv
  report_async/security/ir_rule.xml
  report_async/static/description/icon.png
  report_async/static/description/index.html
  report_async/tests/__init__.py
  report_async/tests/test_report_async.py
  report_async/views/report_async.xml
  report_async/wizard/__init__.py
  report_async/wizard/print_report_wizard.py
  report_async/wizard/print_report_wizard.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_async/odoo/addons/report_async
  setup/report_async/setup.py
Labels: 13.0

#375 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_xlsx/README.rst
  report_xlsx/__manifest__.py
  report_xlsx/static/description/index.html
  report_xlsx_helper/README.rst
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/static/description/index.html
Labels: 15.0

#376 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_xlsx/README.rst
  report_xlsx/__manifest__.py
  report_xlsx/static/description/index.html
  report_xlsx_helper/README.rst
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/static/description/index.html
Labels: 14.0

#377 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  report_xml/README.rst
  report_xml/__manifest__.py
  report_xml/static/description/index.html
Labels: 13.0

#378 Updating from latest OCA 15.0
  README.md
  report_xlsx/README.rst
  report_xlsx/__manifest__.py
  report_xlsx/static/description/index.html
  report_xlsx_helper/README.rst
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/static/description/index.html
Labels: 15.0.project_mi_465

#379 Syncing from upstream OCA/reporting-engine (13.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  report_py3o/__manifest__.py
  report_py3o_fusion_server/__manifest__.py
  report_qweb_signer/README.rst
  report_qweb_signer/__manifest__.py
  report_qweb_signer/data/defaults.xml
  report_qweb_signer/demo/report_partner_demo.xml
  report_qweb_signer/models/ir_actions_report.py
  report_qweb_signer/models/report_certificate.py
  report_qweb_signer/readme/CONTRIBUTORS.rst
  report_qweb_signer/readme/CREDITS.rst
  report_qweb_signer/readme/INSTALL.rst
  report_qweb_signer/readme/ROADMAP.rst
  report_qweb_signer/readme/USAGE.rst
  report_qweb_signer/static/description/index.html
  report_qweb_signer/static/jar/JSignPdf.jar
  report_qweb_signer/static/jar/itext-1.4.8.jar
  report_qweb_signer/static/jar/jPdfSign.jar
  requirements.txt
Labels: 13.0

#380 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_py3o/__manifest__.py
  report_qweb_signer/__manifest__.py
  report_qweb_signer/models/ir_actions_report.py
  report_xml/README.rst
  report_xml/__manifest__.py
  report_xml/static/description/index.html
Labels: 14.0

#381 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  bi_sql_editor/i18n/ca.po
  report_xlsx/i18n/ca.po
  report_xml/README.rst
  report_xml/__manifest__.py
  report_xml/static/description/index.html
Labels: 15.0

#382 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  kpi_dashboard/__manifest__.py
  kpi_dashboard/i18n/kpi_dashboard.pot
  kpi_dashboard/models/kpi_dashboard.py
  kpi_dashboard/views/kpi_dashboard.xml
Labels: 13.0

#383 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  kpi_dashboard_bokeh/README.rst
  kpi_dashboard_bokeh/__init__.py
  kpi_dashboard_bokeh/__manifest__.py
  kpi_dashboard_bokeh/demo/demo_dashboard.xml
  kpi_dashboard_bokeh/i18n/kpi_dashboard_bokeh.pot
  kpi_dashboard_bokeh/models/__init__.py
  kpi_dashboard_bokeh/models/kpi_kpi.py
  kpi_dashboard_bokeh/readme/CONFIGURE.rst
  kpi_dashboard_bokeh/readme/CONTRIBUTORS.rst
  kpi_dashboard_bokeh/readme/DESCRIPTION.rst
  kpi_dashboard_bokeh/static/description/icon.png
  kpi_dashboard_bokeh/static/description/index.html
  kpi_dashboard_bokeh/static/src/js/bokeh_widget.js
  kpi_dashboard_bokeh/static/src/xml/dashboard.xml
  kpi_dashboard_bokeh/views/webclient_templates.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/kpi_dashboard_bokeh/odoo/addons/kpi_dashboard_bokeh
  setup/kpi_dashboard_bokeh/setup.py
Labels: 14.0

#384 Update with contents of 15.0
  README.md
  bi_sql_editor/i18n/ca.po
  report_xlsx/README.rst
  report_xlsx/__manifest__.py
  report_xlsx/i18n/ca.po
  report_xlsx/static/description/index.html
  report_xlsx_helper/README.rst
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/static/description/index.html
  report_xml/README.rst
  report_xml/__manifest__.py
  report_xml/static/description/index.html
Labels: 15.0.project_sy_639
