Repository brain-tec/reporting-engine, pull requests merged in 2022-08, with the labels that each got.

#400 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
Labels: 14.0

#401 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_context/README.rst
  report_context/__init__.py
  report_context/__manifest__.py
  report_context/controllers/__init__.py
  report_context/controllers/main.py
  report_context/data/config_parameter.xml
  report_context/i18n/report_context.pot
  report_context/models/__init__.py
  report_context/models/ir_actions_report.py
  report_context/readme/CONTRIBUTORS.rst
  report_context/readme/DESCRIPTION.rst
  report_context/readme/USAGE.rst
  report_context/static/description/icon.png
  report_context/static/description/index.html
  report_context/tests/__init__.py
  report_context/tests/test_report_context.py
  report_context/views/ir_actions_report.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_context/odoo/addons/report_context
  setup/report_context/setup.py
Labels: 14.0

#402 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
Labels: 15.0

#403 Backmerging 15.0 into 15.0.project_MI_465
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
Labels: 15.0.project_mi_465
