Repository brain-tec/reporting-engine, pull requests merged in 2022-01, with the labels that each got.

#341 [t126885][MIG] report_qweb_element_page_visibility: Migration to 15.0
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.rst
  report_qweb_element_page_visibility/readme/DESCRIPTION.rst
  report_qweb_element_page_visibility/readme/USAGE.rst
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
Labels: feature, 15.0.project_mi_465

#343 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_qweb_encrypt/__manifest__.py
  report_qweb_encrypt/models/ir_actions_report.py
Labels: 14.0

#344 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
  report_xlsx/static/src/js/report/action_manager_report.esm.js
Labels: 15.0

#348 Pre-commit bugfix for report_qweb_element_page_visibility
  report_qweb_element_page_visibility/views/layouts.xml
Labels: bug, 15.0.project_mi_465

#349 Fix tests bi_sql_editor
  bi_sql_editor/models/bi_sql_view.py
Labels: bug, 15.0.project_mi_465
