Repository brain-tec/reporting-engine, pull requests merged in 2022-11, with the labels that each got.

#426 Syncing from upstream OCA/reporting-engine (15.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 15.0

#427 Syncing from upstream OCA/reporting-engine (16.0)
  base_comment_template/i18n/de.po
Labels: 16.0

#428 Backmerge 15.0 into 15.0.project_SY_639
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 15.0.project_sy_639

#429 Syncing from upstream OCA/reporting-engine (14.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
  bi_sql_editor/__manifest__.py
  bi_sql_editor/models/bi_sql_view.py
Labels: 14.0

#431 Syncing from upstream OCA/reporting-engine (15.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 15.0
