Repository brain-tec/reporting-engine, pull requests merged in 2022-05, with the labels that each got.

#385 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  kpi_dashboard/__manifest__.py
  kpi_dashboard/i18n/kpi_dashboard.pot
  kpi_dashboard/models/kpi_dashboard.py
  kpi_dashboard/views/kpi_dashboard.xml
Labels: 14.0

#386 Updating from latest OCA 15.0
  README.md
  bi_sql_editor/i18n/ca.po
  report_xlsx/i18n/ca.po
  report_xml/README.rst
  report_xml/__manifest__.py
  report_xml/static/description/index.html
Labels: 15.0.project_mi_465

#387 Syncing from upstream OCA/reporting-engine (14.0)
  base_comment_template/i18n/it.po
Labels: 14.0

#388 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  base_comment_template/README.rst
  base_comment_template/__manifest__.py
  base_comment_template/static/description/index.html
Labels: 13.0

#389 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_csv/README.rst
  report_csv/__init__.py
  report_csv/__manifest__.py
  report_csv/controllers/__init__.py
  report_csv/controllers/main.py
  report_csv/demo/report.xml
  report_csv/i18n/report_csv.pot
  report_csv/models/__init__.py
  report_csv/models/ir_report.py
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/DESCRIPTION.rst
  report_csv/readme/USAGE.rst
  report_csv/report/__init__.py
  report_csv/report/report_csv.py
  report_csv/report/report_partner_csv.py
  report_csv/static/description/icon.png
  report_csv/static/description/index.html
  report_csv/static/src/js/report/qwebactionmanager.js
  report_csv/tests/__init__.py
  report_csv/tests/test_report.py
  report_csv/views/webclient_templates.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_csv/odoo/addons/report_csv
  setup/report_csv/setup.py
Labels: 14.0
