Repository brain-tec/reporting-engine, pull requests merged in 2022-03, with the labels that each got.

#358 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_qr/README.rst
  report_qr/__init__.py
  report_qr/__manifest__.py
  report_qr/controllers/__init__.py
  report_qr/controllers/qr.py
  report_qr/i18n/report_qr.pot
  report_qr/models/__init__.py
  report_qr/models/ir_actions_report.py
  report_qr/readme/CONTRIBUTORS.rst
  report_qr/readme/DESCRIPTION.rst
  report_qr/readme/USAGE.rst
  report_qr/static/description/icon.png
  report_qr/static/description/index.html
  report_qr/static/description/new_qr.png
  report_qr/static/description/old_qr.png
  report_qr/tests/__init__.py
  report_qr/tests/test_report_qr.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qr/odoo/addons/report_qr
  setup/report_qr/setup.py
Labels: 15.0

#357 Updating from latest OCA 15.0
  README.md
  report_qr/README.rst
  report_qr/__init__.py
  report_qr/__manifest__.py
  report_qr/controllers/__init__.py
  report_qr/controllers/qr.py
  report_qr/i18n/report_qr.pot
  report_qr/models/__init__.py
  report_qr/models/ir_actions_report.py
  report_qr/readme/CONTRIBUTORS.rst
  report_qr/readme/DESCRIPTION.rst
  report_qr/readme/USAGE.rst
  report_qr/static/description/icon.png
  report_qr/static/description/index.html
  report_qr/static/description/new_qr.png
  report_qr/static/description/old_qr.png
  report_qr/tests/__init__.py
  report_qr/tests/test_report_qr.py
  report_xlsx/__manifest__.py
  report_xlsx/models/ir_report.py
  report_xlsx_helper/README.rst
  report_xlsx_helper/__init__.py
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/controllers/__init__.py
  report_xlsx_helper/controllers/main.py
  report_xlsx_helper/i18n/es.po
  report_xlsx_helper/i18n/report_xlsx_helper.pot
  report_xlsx_helper/models/__init__.py
  report_xlsx_helper/models/ir_actions_report.py
  report_xlsx_helper/readme/CONTRIBUTORS.rst
  report_xlsx_helper/readme/DESCRIPTION.rst
  report_xlsx_helper/readme/INSTALL.rst
  report_xlsx_helper/readme/USAGE.rst
  report_xlsx_helper/report/__init__.py
  report_xlsx_helper/report/report_xlsx_abstract.py
  report_xlsx_helper/report/report_xlsx_format.py
  report_xlsx_helper/report/test_partner_report_xlsx.py
  report_xlsx_helper/static/description/icon.png
  report_xlsx_helper/static/description/index.html
  report_xlsx_helper/tests/__init__.py
  report_xlsx_helper/tests/test_report_xlsx_helper.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qr/odoo/addons/report_qr
  setup/report_qr/setup.py
  setup/report_xlsx_helper/odoo/addons/report_xlsx_helper
  setup/report_xlsx_helper/setup.py
Labels: 15.0.project_mi_465

#359 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  report_xlsx_helper/README.rst
  report_xlsx_helper/__manifest__.py
  report_xlsx_helper/static/description/index.html
Labels: 13.0

#360 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_qweb_parameter/README.rst
  report_qweb_parameter/__init__.py
  report_qweb_parameter/__manifest__.py
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/i18n/es.po
  report_qweb_parameter/i18n/fr.po
  report_qweb_parameter/i18n/it.po
  report_qweb_parameter/i18n/pt.po
  report_qweb_parameter/i18n/report_qweb_parameter.pot
  report_qweb_parameter/models/__init__.py
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/readme/CONTRIBUTORS.rst
  report_qweb_parameter/readme/DESCRIPTION.rst
  report_qweb_parameter/readme/USAGE.rst
  report_qweb_parameter/static/description/icon.png
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/__init__.py
  report_qweb_parameter/tests/test_report_qweb_parameter.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qweb_parameter/odoo/addons/report_qweb_parameter
  setup/report_qweb_parameter/setup.py
Labels: 15.0

#361 Updating from latest OCA 15.0
  README.md
  report_qweb_parameter/README.rst
  report_qweb_parameter/__init__.py
  report_qweb_parameter/__manifest__.py
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/i18n/es.po
  report_qweb_parameter/i18n/fr.po
  report_qweb_parameter/i18n/it.po
  report_qweb_parameter/i18n/pt.po
  report_qweb_parameter/i18n/report_qweb_parameter.pot
  report_qweb_parameter/models/__init__.py
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/readme/CONTRIBUTORS.rst
  report_qweb_parameter/readme/DESCRIPTION.rst
  report_qweb_parameter/readme/USAGE.rst
  report_qweb_parameter/static/description/icon.png
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/__init__.py
  report_qweb_parameter/tests/test_report_qweb_parameter.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qweb_parameter/odoo/addons/report_qweb_parameter
  setup/report_qweb_parameter/setup.py
Labels: 15.0.project_mi_465

#362 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  bi_sql_editor/__manifest__.py
  bi_sql_editor/models/bi_sql_view.py
Labels: 15.0
