Repository brain-tec/reporting-engine, pull requests merged in 2023-03, with the labels that each got.

#467 Syncing from upstream OCA/reporting-engine (9.0)
  report_wkhtmltopdf_param/i18n/it.po
Labels: 9.0

#469 Syncing from upstream OCA/reporting-engine (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 14.0

#470 Syncing from upstream OCA/reporting-engine (15.0)
  .copier-answers.yml
Labels: 15.0

#471 Syncing from upstream OCA/reporting-engine (16.0)
  .copier-answers.yml
Labels: 16.0

#472 Syncing from upstream OCA/reporting-engine (12.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 12.0

#473 Syncing from upstream OCA/reporting-engine (13.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 13.0

#476 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 14.0

#478 Syncing from upstream OCA/reporting-engine (12.0)
  bi_view_editor/i18n/it.po
Labels: 12.0

#479 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 15.0

#480 Syncing from upstream OCA/reporting-engine (14.0)
  report_async/i18n/it.po
Labels: 14.0

#481 Syncing from upstream OCA/reporting-engine (15.0)
  base_comment_template/i18n/it.po
  bi_view_editor/i18n/it.po
Labels: 15.0

#482 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  base_comment_template/i18n/it.po
  bi_sql_editor/i18n/it.po
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.rst
  report_qweb_element_page_visibility/readme/CREDITS.rst
  report_qweb_element_page_visibility/readme/DESCRIPTION.rst
  report_qweb_element_page_visibility/readme/USAGE.rst
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
  report_wkhtmltopdf_param/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qweb_element_page_visibility/odoo/addons/report_qweb_element_page_visibility
  setup/report_qweb_element_page_visibility/setup.py
  sql_export/i18n/it.po
Labels: 16.0

#483 [bt#22264] Fix Crash in Report Controller
  report_xlsx/controllers/main.py
Labels: 15.0.project_sv_559

#485 Syncing from upstream OCA/reporting-engine (12.0)
  bi_sql_editor/i18n/it.po
  bi_view_editor/i18n/it.po
  kpi/i18n/it.po
  report_py3o/i18n/it.po
  report_py3o_fusion_server/i18n/it.po
  report_qweb_signer/i18n/it.po
  report_wkhtmltopdf_param/i18n/it.po
Labels: 12.0

#486 Syncing from upstream OCA/reporting-engine (13.0)
  base_comment_template/i18n/it.po
  bi_sql_editor/i18n/it.po
  kpi/i18n/it.po
  report_csv/i18n/it.po
  report_py3o/i18n/it.po
  report_py3o_fusion_server/i18n/it.po
  report_qweb_signer/i18n/it.po
  report_wkhtmltopdf_param/i18n/it.po
Labels: 13.0

#488 Syncing from upstream OCA/reporting-engine (15.0)
  bi_sql_editor/i18n/it.po
  report_wkhtmltopdf_param/i18n/it.po
  sql_export/i18n/it.po
  sql_request_abstract/i18n/it.po
Labels: 15.0
