Repository brain-tec/reporting-engine, pull requests merged in 2023-08, with the labels that each got.

#558 Syncing from upstream OCA/reporting-engine (14.0)
  report_qweb_signer/i18n/ca.po
Labels: 14.0

#559 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 15.0

#560 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_qweb_encrypt/README.rst
  report_qweb_encrypt/__init__.py
  report_qweb_encrypt/__manifest__.py
  report_qweb_encrypt/controllers/__init__.py
  report_qweb_encrypt/controllers/main.py
  report_qweb_encrypt/i18n/es.po
  report_qweb_encrypt/i18n/report_qweb_encrypt.pot
  report_qweb_encrypt/models/__init__.py
  report_qweb_encrypt/models/ir_actions_report.py
  report_qweb_encrypt/readme/CONTRIBUTORS.rst
  report_qweb_encrypt/readme/DESCRIPTION.rst
  report_qweb_encrypt/readme/USAGE.rst
  report_qweb_encrypt/static/description/icon.png
  report_qweb_encrypt/static/description/index.html
  report_qweb_encrypt/static/src/report/action_manager_report.esm.js
  report_qweb_encrypt/static/src/report/encrypt_dialog.xml
  report_qweb_encrypt/tests/__init__.py
  report_qweb_encrypt/tests/test_report_qweb_encrypt.py
  report_qweb_encrypt/views/ir_actions_report.xml
  setup/_metapackage/setup.py
  setup/report_qweb_encrypt/odoo/addons/report_qweb_encrypt
  setup/report_qweb_encrypt/setup.py
Labels: 16.0

#561 Syncing from upstream OCA/reporting-engine (14.0)
  bi_sql_editor/i18n/pl.po
Labels: 14.0

#563 Syncing from upstream OCA/reporting-engine (12.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  README.md
  report_async/__manifest__.py
  report_async/i18n/report_async.pot
  report_async/models/ir_report.py
  report_async/models/report_async.py
  report_async/views/report_async.xml
Labels: 12.0

#564 Syncing from upstream OCA/reporting-engine (15.0)
  bi_sql_editor/i18n/es_MX.po
  report_py3o/i18n/es_AR.po
Labels: 15.0

#565 [t140653] Avoiding ERROR in log with tests of report_qweb_pdf_watermark
  report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
Labels: 16.0.project_xp_228

#566 Syncing from upstream OCA/reporting-engine (16.0)
  bi_sql_editor/i18n/bi_sql_editor.pot
  report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
  sql_export/i18n/sql_export.pot
  sql_request_abstract/i18n/sql_request_abstract.pot
Labels: 16.0
