Repository brain-tec/reporting-engine, pull requests merged in 2023-04, with the labels that each got.

#489 Syncing from upstream OCA/reporting-engine (13.0)
  report_py3o_fusion_server/i18n/sl.po
Labels: 13.0

#490 Syncing from upstream OCA/reporting-engine (14.0)
  bi_view_editor/i18n/sl.po
  report_py3o/i18n/sl.po
  report_py3o_fusion_server/i18n/sl.po
  report_wkhtmltopdf_param/i18n/sl.po
Labels: 14.0

#491 Syncing from upstream OCA/reporting-engine (15.0)
  bi_sql_editor/i18n/sl.po
  report_wkhtmltopdf_param/i18n/sl.po
  sql_export/i18n/sl.po
  sql_request_abstract/i18n/sl.po
Labels: 15.0

#492 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_qweb_pdf_watermark/README.rst
  report_qweb_pdf_watermark/__init__.py
  report_qweb_pdf_watermark/__manifest__.py
  report_qweb_pdf_watermark/demo/report.xml
  report_qweb_pdf_watermark/i18n/ca.po
  report_qweb_pdf_watermark/i18n/da.po
  report_qweb_pdf_watermark/i18n/de.po
  report_qweb_pdf_watermark/i18n/el_GR.po
  report_qweb_pdf_watermark/i18n/es.po
  report_qweb_pdf_watermark/i18n/es_CO.po
  report_qweb_pdf_watermark/i18n/fr.po
  report_qweb_pdf_watermark/i18n/gl.po
  report_qweb_pdf_watermark/i18n/hr.po
  report_qweb_pdf_watermark/i18n/hr_HR.po
  report_qweb_pdf_watermark/i18n/it.po
  report_qweb_pdf_watermark/i18n/nb_NO.po
  report_qweb_pdf_watermark/i18n/nl_NL.po
  report_qweb_pdf_watermark/i18n/pl.po
  report_qweb_pdf_watermark/i18n/pt.po
  report_qweb_pdf_watermark/i18n/pt_BR.po
  report_qweb_pdf_watermark/i18n/pt_PT.po
  report_qweb_pdf_watermark/i18n/report_qweb_pdf_watermark.pot
  report_qweb_pdf_watermark/i18n/sl.po
  report_qweb_pdf_watermark/i18n/tr.po
  report_qweb_pdf_watermark/i18n/tr_TR.po
  report_qweb_pdf_watermark/models/__init__.py
  report_qweb_pdf_watermark/models/report.py
  report_qweb_pdf_watermark/models/res_company.py
  report_qweb_pdf_watermark/readme/CONTRIBUTORS.rst
  report_qweb_pdf_watermark/readme/DESCRIPTION.rst
  report_qweb_pdf_watermark/readme/HISTORY.rst
  report_qweb_pdf_watermark/readme/INSTALL.rst
  report_qweb_pdf_watermark/readme/ROADMAP.rst
  report_qweb_pdf_watermark/readme/USAGE.rst
  report_qweb_pdf_watermark/static/description/icon.png
  report_qweb_pdf_watermark/static/description/index.html
  report_qweb_pdf_watermark/static/src/css/report_qweb_pdf_watermark.css
  report_qweb_pdf_watermark/tests/__init__.py
  report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
  report_qweb_pdf_watermark/views/ir_actions_report_xml.xml
  report_qweb_pdf_watermark/views/res_company.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qweb_pdf_watermark/odoo/addons/report_qweb_pdf_watermark
  setup/report_qweb_pdf_watermark/setup.py
Labels: 16.0

#493 Syncing from upstream OCA/reporting-engine (16.0)
  report_qweb_pdf_watermark/i18n/da.po
  report_qweb_pdf_watermark/i18n/de.po
  report_qweb_pdf_watermark/i18n/el_GR.po
  report_qweb_pdf_watermark/i18n/es.po
  report_qweb_pdf_watermark/i18n/es_CO.po
  report_qweb_pdf_watermark/i18n/fr.po
  report_qweb_pdf_watermark/i18n/gl.po
  report_qweb_pdf_watermark/i18n/hr.po
  report_qweb_pdf_watermark/i18n/hr_HR.po
  report_qweb_pdf_watermark/i18n/it.po
  report_qweb_pdf_watermark/i18n/nb_NO.po
  report_qweb_pdf_watermark/i18n/nl_NL.po
  report_qweb_pdf_watermark/i18n/pl.po
  report_qweb_pdf_watermark/i18n/pt.po
  report_qweb_pdf_watermark/i18n/pt_BR.po
  report_qweb_pdf_watermark/i18n/pt_PT.po
  report_qweb_pdf_watermark/i18n/sl.po
  report_qweb_pdf_watermark/i18n/tr.po
  report_qweb_pdf_watermark/i18n/tr_TR.po
Labels: 16.0

#494 Syncing from upstream OCA/reporting-engine (15.0)
  base_comment_template/i18n/es_AR.po
  bi_sql_editor/i18n/es_AR.po
  bi_view_editor/i18n/es_AR.po
  sql_export/i18n/es_AR.po
Labels: 15.0

#495 Syncing from upstream OCA/reporting-engine (16.0)
  bi_sql_editor/i18n/es_AR.po
Labels: 16.0

#496 Syncing from upstream OCA/reporting-engine (15.0)
  base_comment_template/i18n/es_AR.po
Labels: 15.0

#499 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  report_py3o/__manifest__.py
  report_qweb_pdf_watermark/__manifest__.py
  report_xlsx/__manifest__.py
  report_xml/__manifest__.py
  requirements.txt
Labels: 13.0

#500 Syncing from upstream OCA/reporting-engine (14.0)
  base_comment_template/i18n/sl.po
  bi_sql_editor/i18n/sl.po
  report_qweb_signer/i18n/sl.po
Labels: 14.0

#501 Syncing from upstream OCA/reporting-engine (16.0)
  base_comment_template/i18n/sl.po
  bi_sql_editor/i18n/sl.po
  report_wkhtmltopdf_param/i18n/sl.po
  sql_export/i18n/sl.po
Labels: 16.0

#502 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
Labels: 15.0

#503 Update project branch with the newest 15.0
  README.md
  base_comment_template/i18n/es_AR.po
  bi_sql_editor/i18n/es_AR.po
  bi_sql_editor/i18n/it.po
  bi_sql_editor/i18n/sl.po
  bi_view_editor/i18n/es_AR.po
  report_wkhtmltopdf_param/i18n/it.po
  report_wkhtmltopdf_param/i18n/sl.po
  report_xlsx/__manifest__.py
  report_xlsx/controllers/main.py
  sql_export/i18n/es_AR.po
  sql_export/i18n/it.po
  sql_export/i18n/sl.po
  sql_request_abstract/i18n/it.po
  sql_request_abstract/i18n/sl.po
Labels: 15.0.project_sy_639

#504 Syncing from upstream OCA/reporting-engine (13.0)
  kpi/i18n/it.po
Labels: 13.0

#505 Syncing from upstream OCA/reporting-engine (13.0)
  README.md
  base_comment_template/__manifest__.py
  base_comment_template/models/comment_template.py
  base_comment_template/tests/test_base_comment_template.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 13.0

#506 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  base_comment_template/__manifest__.py
  base_comment_template/models/comment_template.py
  base_comment_template/tests/test_base_comment_template.py
Labels: 14.0

#507 Revert "[bt#22264] Fix Crash in Report Controller"
  report_xlsx/controllers/main.py
Labels: 15.0.project_sv_559
