Repository brain-tec/reporting-engine, pull requests merged in 2024-03, with the labels that each got.

#649 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_qr/README.rst
  report_qr/__init__.py
  report_qr/__manifest__.py
  report_qr/controllers/__init__.py
  report_qr/controllers/qr.py
  report_qr/i18n/ca.po
  report_qr/i18n/it.po
  report_qr/i18n/report_qr.pot
  report_qr/models/__init__.py
  report_qr/models/ir_actions_report.py
  report_qr/readme/CONTRIBUTORS.rst
  report_qr/readme/DESCRIPTION.rst
  report_qr/readme/USAGE.rst
  report_qr/static/description/icon.png
  report_qr/static/description/index.html
  report_qr/static/description/new_qr.png
  report_qr/static/description/old_qr.png
  report_qr/tests/__init__.py
  report_qr/tests/test_report_qr.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qr/odoo/addons/report_qr
  setup/report_qr/setup.py
Labels: 16.0

#650 Syncing from upstream OCA/reporting-engine (16.0)
  report_qr/i18n/it.po
Labels: 16.0

#651 Syncing from upstream OCA/reporting-engine (15.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sql_export_mail/odoo/addons/sql_export_mail
  setup/sql_export_mail/setup.py
  sql_export_mail/README.rst
  sql_export_mail/__init__.py
  sql_export_mail/__manifest__.py
  sql_export_mail/data/mail_template.xml
  sql_export_mail/i18n/ca.po
  sql_export_mail/i18n/fr.po
  sql_export_mail/i18n/it.po
  sql_export_mail/i18n/sql_export_mail.pot
  sql_export_mail/models/__init__.py
  sql_export_mail/models/sql_export.py
  sql_export_mail/readme/CONFIGURE.rst
  sql_export_mail/readme/CONTRIBUTORS.rst
  sql_export_mail/readme/DESCRIPTION.rst
  sql_export_mail/static/description/icon.png
  sql_export_mail/static/description/index.html
  sql_export_mail/tests/__init__.py
  sql_export_mail/tests/test_sql_query_mail.py
  sql_export_mail/views/sql_export_view.xml
Labels: 15.0

#653 [bt#26060] SQL Export mail
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sql_export_mail/odoo/addons/sql_export_mail
  setup/sql_export_mail/setup.py
  sql_export_mail/README.rst
  sql_export_mail/__init__.py
  sql_export_mail/__manifest__.py
  sql_export_mail/data/mail_template.xml
  sql_export_mail/i18n/ca.po
  sql_export_mail/i18n/fr.po
  sql_export_mail/i18n/it.po
  sql_export_mail/i18n/sql_export_mail.pot
  sql_export_mail/models/__init__.py
  sql_export_mail/models/sql_export.py
  sql_export_mail/readme/CONFIGURE.rst
  sql_export_mail/readme/CONTRIBUTORS.rst
  sql_export_mail/readme/DESCRIPTION.rst
  sql_export_mail/static/description/icon.png
  sql_export_mail/static/description/index.html
  sql_export_mail/tests/__init__.py
  sql_export_mail/tests/test_sql_query_mail.py
  sql_export_mail/views/sql_export_view.xml
Labels: 15.0.project_sy_639.test

#654 Syncing from upstream OCA/reporting-engine (12.0)
  bi_view_editor/i18n/it.po
Labels: 12.0

#655 Syncing from upstream OCA/reporting-engine (14.0)
  bi_sql_editor/i18n/es.po
  bi_view_editor/i18n/es.po
  kpi_dashboard/i18n/es.po
  report_async/i18n/es.po
  report_label/i18n/es.po
  report_layout_config/i18n/es.po
  report_py3o_fusion_server/i18n/es.po
Labels: 14.0

#656 Syncing from upstream OCA/reporting-engine (12.0)
  kpi/i18n/it.po
Labels: 12.0

#657 Syncing from upstream OCA/reporting-engine (13.0)
  kpi/i18n/it.po
Labels: 13.0

#658 Syncing from upstream OCA/reporting-engine (14.0)
  base_comment_template/i18n/es.po
  bi_sql_editor/i18n/es.po
  report_fillpdf/i18n/es.po
  report_py3o/i18n/es.po
  report_qweb_encrypt/i18n/es.po
  report_qweb_signer/i18n/es.po
  report_xlsx_helper/i18n/es.po
  report_xml/i18n/es.po
Labels: 14.0
