Repository brain-tec/reporting-engine, pull requests merged in 2024-04, with the labels that each got.

#652 [bt#26060] SQL Export mail
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sql_export_mail/odoo/addons/sql_export_mail
  setup/sql_export_mail/setup.py
  sql_export_mail/README.rst
  sql_export_mail/__init__.py
  sql_export_mail/__manifest__.py
  sql_export_mail/data/mail_template.xml
  sql_export_mail/i18n/ca.po
  sql_export_mail/i18n/fr.po
  sql_export_mail/i18n/it.po
  sql_export_mail/i18n/sql_export_mail.pot
  sql_export_mail/models/__init__.py
  sql_export_mail/models/sql_export.py
  sql_export_mail/readme/CONFIGURE.rst
  sql_export_mail/readme/CONTRIBUTORS.rst
  sql_export_mail/readme/DESCRIPTION.rst
  sql_export_mail/static/description/icon.png
  sql_export_mail/static/description/index.html
  sql_export_mail/tests/__init__.py
  sql_export_mail/tests/test_sql_query_mail.py
  sql_export_mail/views/sql_export_view.xml
Labels: 15.0.project_sy_639

#659 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  bi_sql_editor/i18n/it.po
  report_py3o/README.rst
  report_py3o/__manifest__.py
  report_py3o/static/description/index.html
  report_py3o_fusion_server/i18n/it.po
  report_xlsx/README.rst
  report_xlsx/__manifest__.py
  report_xlsx/static/description/index.html
  report_xml/README.rst
  report_xml/__manifest__.py
  report_xml/static/description/index.html
  requirements.txt
Labels: 16.0

#660 Syncing from upstream OCA/reporting-engine (17.0)
  bi_sql_editor/i18n/it.po
Labels: 17.0

#661 Syncing from upstream OCA/reporting-engine (14.0)
  kpi_dashboard_bokeh/i18n/es.po
  report_context/i18n/es.po
  report_csv/i18n/es.po
  report_qweb_parameter/i18n/es.po
  report_qweb_pdf_watermark/i18n/es.po
  report_wkhtmltopdf_param/i18n/es.po
  report_xlsx/i18n/es.po
  report_xlsx_helper_demo/i18n/es.po
Labels: 14.0

#663 Syncing from upstream OCA/reporting-engine (16.0)
  bi_view_editor/i18n/it.po
  report_qweb_signer/i18n/it.po
Labels: 16.0
