Repository brain-tec/reporting-engine, pull requests merged in 2024-06, with the labels that each got.

#676 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_generate_helper/README.rst
  report_generate_helper/__init__.py
  report_generate_helper/__manifest__.py
  report_generate_helper/i18n/report_generate_helper.pot
  report_generate_helper/models/__init__.py
  report_generate_helper/models/base.py
  report_generate_helper/models/ir_actions_report.py
  report_generate_helper/readme/CONTRIBUTORS.rst
  report_generate_helper/readme/DESCRIPTION.rst
  report_generate_helper/static/description/icon.png
  report_generate_helper/static/description/index.html
  report_generate_helper/tests/__init__.py
  report_generate_helper/tests/test_report_generate_helper.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_generate_helper/odoo/addons/report_generate_helper
  setup/report_generate_helper/setup.py
Labels: 16.0

#677 Syncing from upstream OCA/reporting-engine (12.0)
  README.md
  bi_sql_editor/README.rst
  bi_sql_editor/__manifest__.py
  bi_sql_editor/models/bi_sql_view.py
  bi_sql_editor/static/description/index.html
Labels: 12.0

#678 Syncing from upstream OCA/reporting-engine (16.0)
  report_generate_helper/i18n/it.po
Labels: 16.0

#683 Syncing from upstream OCA/reporting-engine (16.0)
  bi_sql_editor/i18n/it.po
  report_text_format_option/i18n/it.po
Labels: 16.0

#684 Syncing from upstream OCA/reporting-engine (17.0)
  bi_sql_editor/i18n/sv.po
  report_wkhtmltopdf_param/i18n/sv.po
Labels: 17.0

#685 Syncing from upstream OCA/reporting-engine (17.0)
  report_xlsx/i18n/sv.po
  report_xml/i18n/sv.po
  sql_request_abstract/i18n/sv.po
Labels: 17.0

#686 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_display_name_in_footer/README.rst
  report_display_name_in_footer/__init__.py
  report_display_name_in_footer/__manifest__.py
  report_display_name_in_footer/data/report_data.xml
  report_display_name_in_footer/i18n/it.po
  report_display_name_in_footer/i18n/report_display_name_in_footer.pot
  report_display_name_in_footer/models/__init__.py
  report_display_name_in_footer/models/ir_actions_report.py
  report_display_name_in_footer/readme/CONFIGURE.md
  report_display_name_in_footer/readme/CONTEXT.md
  report_display_name_in_footer/readme/CONTRIBUTORS.md
  report_display_name_in_footer/readme/DESCRIPTION.md
  report_display_name_in_footer/readme/USAGE.md
  report_display_name_in_footer/static/description/icon.png
  report_display_name_in_footer/static/description/index.html
  report_display_name_in_footer/views/report_templates.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_display_name_in_footer/odoo/addons/report_display_name_in_footer
  setup/report_display_name_in_footer/setup.py
Labels: 16.0

#688 Syncing from upstream OCA/reporting-engine (17.0)
  README.md
  report_layout_config/README.rst
  report_layout_config/__init__.py
  report_layout_config/__manifest__.py
  report_layout_config/data/report_layout.xml
  report_layout_config/i18n/es.po
  report_layout_config/i18n/report_layout_config.pot
  report_layout_config/models/__init__.py
  report_layout_config/models/base_document_layout.py
  report_layout_config/models/res_company.py
  report_layout_config/pyproject.toml
  report_layout_config/readme/CONTRIBUTORS.md
  report_layout_config/readme/DESCRIPTION.md
  report_layout_config/readme/USAGE.md
  report_layout_config/static/description/icon.png
  report_layout_config/static/description/index.html
  report_layout_config/static/img/preview_standard.png
  report_layout_config/static/pdf/preview_standard.pdf
  report_layout_config/static/src/scss/style.scss
  report_layout_config/templates/report_templates.xml
  report_layout_config/views/document_layout.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#689 Syncing from upstream OCA/reporting-engine (17.0)
  report_layout_config/i18n/it.po
Labels: 17.0

#690 17.0 mig report qweb element page visibility
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/pyproject.toml
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.md
  report_qweb_element_page_visibility/readme/CREDITS.md
  report_qweb_element_page_visibility/readme/DESCRIPTION.md
  report_qweb_element_page_visibility/readme/USAGE.md
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 17.0.project_t_576.t148365

#691 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_display_name_in_footer/README.rst
  report_display_name_in_footer/__manifest__.py
  report_display_name_in_footer/data/report_data.xml
  report_display_name_in_footer/readme/ROADMAP.md
  report_display_name_in_footer/static/description/index.html
Labels: 16.0

#692 Syncing from upstream OCA/reporting-engine (16.0)
  sql_export/i18n/it.po
Labels: 16.0

#693 Syncing from upstream OCA/reporting-engine (16.0)
  base_comment_template/i18n/sv.po
  bi_sql_editor/i18n/sv.po
  bi_view_editor/i18n/sv.po
  report_py3o/i18n/sv.po
  report_py3o_fusion_server/i18n/sv.po
Labels: 16.0
