Repository brain-tec/reporting-engine, pull requests merged in 2025-01, with the labels that each got.

#747 Syncing from upstream OCA/reporting-engine (16.0)
  report_xlsx/i18n/fr.po
Labels: 16.0

#748 Syncing from upstream OCA/reporting-engine (12.0)
  README.md
  report_pdf_zip_download/README.rst
  report_pdf_zip_download/__init__.py
  report_pdf_zip_download/__manifest__.py
  report_pdf_zip_download/controllers/__init__.py
  report_pdf_zip_download/controllers/main.py
  report_pdf_zip_download/i18n/report_pdf_zip_download.pot
  report_pdf_zip_download/models/__init__.py
  report_pdf_zip_download/models/ir_actions_report.py
  report_pdf_zip_download/readme/CONFIGURE.rst
  report_pdf_zip_download/readme/CONTRIBUTORS.rst
  report_pdf_zip_download/readme/DESCRIPTION.rst
  report_pdf_zip_download/static/description/icon.png
  report_pdf_zip_download/static/description/index.html
  report_pdf_zip_download/static/src/js/action_manager_report.js
  report_pdf_zip_download/views/ir_actions_report_views.xml
  report_pdf_zip_download/views/web_client_templates.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_pdf_zip_download/odoo/addons/report_pdf_zip_download
  setup/report_pdf_zip_download/setup.py
Labels: 12.0

#749 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_csv/README.rst
  report_csv/__manifest__.py
  report_csv/i18n/es.po
  report_csv/i18n/it.po
  report_csv/i18n/report_csv.pot
  report_csv/models/ir_report.py
  report_csv/readme/CONFIGURE.rst
  report_csv/readme/CONTRIBUTORS.rst
  report_csv/readme/USAGE.rst
  report_csv/report/report_csv.py
  report_csv/static/description/index.html
  report_csv/tests/test_report.py
  report_csv/views/ir_actions_views.xml
Labels: 14.0

#750 Syncing from upstream OCA/reporting-engine (17.0)
  README.md
  setup/_metapackage/pyproject.toml
  sql_export_mail/README.rst
  sql_export_mail/__init__.py
  sql_export_mail/__manifest__.py
  sql_export_mail/data/mail_template.xml
  sql_export_mail/i18n/ca.po
  sql_export_mail/i18n/fr.po
  sql_export_mail/i18n/it.po
  sql_export_mail/i18n/sql_export_mail.pot
  sql_export_mail/models/__init__.py
  sql_export_mail/models/sql_export.py
  sql_export_mail/pyproject.toml
  sql_export_mail/readme/CONFIGURE.md
  sql_export_mail/readme/CONTRIBUTORS.md
  sql_export_mail/readme/DESCRIPTION.md
  sql_export_mail/static/description/icon.png
  sql_export_mail/static/description/index.html
  sql_export_mail/tests/__init__.py
  sql_export_mail/tests/test_sql_query_mail.py
  sql_export_mail/views/sql_export_view.xml
Labels: 17.0

#741 [t154506][18.0][MIG] report_qweb_element_page_visibility: Migration to 18.
  bi_sql_editor/i18n/it.po
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/pyproject.toml
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.md
  report_qweb_element_page_visibility/readme/CREDITS.md
  report_qweb_element_page_visibility/readme/DESCRIPTION.md
  report_qweb_element_page_visibility/readme/USAGE.md
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 18.0.project_sv_559

#751 Syncing from upstream OCA/reporting-engine (17.0)
  sql_export_mail/i18n/it.po
Labels: 17.0

#752 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_qweb_parameter/README.rst
  report_qweb_parameter/__manifest__.py
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/readme/CONTRIBUTORS.rst
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/test_report_qweb_parameter.py
Labels: 16.0

#753 Syncing from upstream OCA/reporting-engine (17.0)
  README.md
  report_qweb_parameter/README.rst
  report_qweb_parameter/__manifest__.py
  report_qweb_parameter/demo/test_report_field_length.xml
  report_qweb_parameter/models/ir_qweb.py
  report_qweb_parameter/readme/CONTRIBUTORS.md
  report_qweb_parameter/static/description/index.html
  report_qweb_parameter/tests/test_report_qweb_parameter.py
Labels: 17.0

#756 Syncing from upstream OCA/reporting-engine (18.0)
  sql_export/i18n/it.po
Labels: 18.0

#757 Syncing from upstream OCA/reporting-engine (16.0)
  report_py3o/i18n/it.po
Labels: 16.0
