Repository brain-tec/reporting-engine, pull requests merged in 2025-03, with the labels that each got.

#767 Syncing from upstream OCA/reporting-engine (17.0)
  README.md
  report_csv/README.rst
  report_csv/__init__.py
  report_csv/__manifest__.py
  report_csv/controllers/__init__.py
  report_csv/controllers/main.py
  report_csv/demo/report.xml
  report_csv/i18n/es.po
  report_csv/i18n/it.po
  report_csv/i18n/report_csv.pot
  report_csv/models/__init__.py
  report_csv/models/ir_report.py
  report_csv/pyproject.toml
  report_csv/readme/CONFIGURE.md
  report_csv/readme/CONTRIBUTORS.md
  report_csv/readme/DESCRIPTION.md
  report_csv/readme/USAGE.md
  report_csv/report/__init__.py
  report_csv/report/report_csv.py
  report_csv/report/report_partner_csv.py
  report_csv/static/description/icon.png
  report_csv/static/description/index.html
  report_csv/static/src/js/report/qwebactionmanager.esm.js
  report_csv/tests/__init__.py
  report_csv/tests/test_report.py
  report_csv/views/ir_actions_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#768 Syncing from upstream OCA/reporting-engine (17.0)
  README.md
  report_csv/README.rst
  report_csv/__manifest__.py
  report_csv/static/description/index.html
Labels: 17.0

#769 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_py3o/README.rst
  report_py3o/__manifest__.py
  report_py3o/static/description/index.html
  report_py3o/tests/test_report_py3o.py
Labels: 16.0

#771 Syncing from upstream OCA/reporting-engine (18.0)
  README.md
  report_qweb_element_page_visibility/README.rst
  report_qweb_element_page_visibility/__init__.py
  report_qweb_element_page_visibility/__manifest__.py
  report_qweb_element_page_visibility/i18n/it.po
  report_qweb_element_page_visibility/i18n/report_qweb_element_page_visibility.pot
  report_qweb_element_page_visibility/pyproject.toml
  report_qweb_element_page_visibility/readme/CONTRIBUTORS.md
  report_qweb_element_page_visibility/readme/CREDITS.md
  report_qweb_element_page_visibility/readme/DESCRIPTION.md
  report_qweb_element_page_visibility/readme/USAGE.md
  report_qweb_element_page_visibility/static/description/icon.png
  report_qweb_element_page_visibility/static/description/index.html
  report_qweb_element_page_visibility/views/layouts.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#772 [t154506][18.0][MIG] report_qweb_element_page_visibility: Migration to 18.0
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 18.0.t154506

#773 [t154506][18.0][MIG] report_qweb_element_page_visibility: Migration to 18.
  report_qweb_element_page_visibility/views/layouts.xml
Labels: 18.0.project_sv_559

#774 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_qweb_signer/README.rst
  report_qweb_signer/__manifest__.py
  report_qweb_signer/models/ir_actions_report.py
  report_qweb_signer/static/description/index.html
Labels: 16.0

#776 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_qweb_field_option/README.rst
  report_qweb_field_option/__init__.py
  report_qweb_field_option/__manifest__.py
  report_qweb_field_option/i18n/report_qweb_field_option.pot
  report_qweb_field_option/models/__init__.py
  report_qweb_field_option/models/ir_qweb.py
  report_qweb_field_option/models/qweb_field_options.py
  report_qweb_field_option/readme/CONFIGURE.rst
  report_qweb_field_option/readme/CONTRIBUTORS.rst
  report_qweb_field_option/readme/DESCRIPTION.rst
  report_qweb_field_option/readme/ROADMAP.rst
  report_qweb_field_option/readme/USAGE.rst
  report_qweb_field_option/security/ir.model.access.csv
  report_qweb_field_option/security/qweb_field_options_security.xml
  report_qweb_field_option/static/description/icon.png
  report_qweb_field_option/static/description/index.html
  report_qweb_field_option/tests/__init__.py
  report_qweb_field_option/tests/test_models.py
  report_qweb_field_option/tests/test_report_qweb_field_options.py
  report_qweb_field_option/views/qweb_field_options_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/report_qweb_field_option/odoo/addons/report_qweb_field_option
  setup/report_qweb_field_option/setup.py
  test-requirements.txt
Labels: 16.0

#778 Syncing from upstream OCA/reporting-engine (14.0)
  report_qr/i18n/it.po
Labels: 14.0

#779 Syncing from upstream OCA/reporting-engine (16.0)
  report_qweb_field_option/i18n/it.po
Labels: 16.0

#780 Syncing from upstream OCA/reporting-engine (18.0)
  README.md
  requirements.txt
  setup/_metapackage/pyproject.toml
  sql_export_excel/README.rst
  sql_export_excel/__init__.py
  sql_export_excel/__manifest__.py
  sql_export_excel/i18n/ca.po
  sql_export_excel/i18n/es.po
  sql_export_excel/i18n/it.po
  sql_export_excel/i18n/sql_export_excel.pot
  sql_export_excel/models/__init__.py
  sql_export_excel/models/sql_export.py
  sql_export_excel/pyproject.toml
  sql_export_excel/readme/CONFIGURE.md
  sql_export_excel/readme/CONTRIBUTORS.md
  sql_export_excel/readme/DESCRIPTION.md
  sql_export_excel/static/description/icon.png
  sql_export_excel/static/description/index.html
  sql_export_excel/tests/__init__.py
  sql_export_excel/tests/test_sql_query_excel.py
  sql_export_excel/views/sql_export_view.xml
Labels: 18.0

#781 Syncing from upstream OCA/reporting-engine (14.0)
  README.md
  report_label/README.rst
  report_label/__manifest__.py
  report_label/models/ir_actions_server.py
  report_label/static/description/index.html
Labels: 14.0

#782 Syncing from upstream OCA/reporting-engine (17.0)
  README.md
  requirements.txt
  setup/_metapackage/pyproject.toml
  sql_export_excel/README.rst
  sql_export_excel/__init__.py
  sql_export_excel/__manifest__.py
  sql_export_excel/i18n/ca.po
  sql_export_excel/i18n/es.po
  sql_export_excel/i18n/it.po
  sql_export_excel/i18n/sql_export_excel.pot
  sql_export_excel/models/__init__.py
  sql_export_excel/models/sql_export.py
  sql_export_excel/pyproject.toml
  sql_export_excel/readme/CONFIGURE.md
  sql_export_excel/readme/CONTRIBUTORS.md
  sql_export_excel/readme/DESCRIPTION.md
  sql_export_excel/static/description/icon.png
  sql_export_excel/static/description/index.html
  sql_export_excel/tests/__init__.py
  sql_export_excel/tests/test_sql_query_excel.py
  sql_export_excel/views/sql_export_view.xml
Labels: 17.0

#783 Syncing from upstream OCA/reporting-engine (16.0)
  README.md
  report_substitute/README.rst
  report_substitute/__manifest__.py
  report_substitute/models/mail_thread.py
  report_substitute/static/description/index.html
  report_substitute/wizards/mail_compose_message.py
Labels: 16.0

#784 Syncing from upstream OCA/reporting-engine (16.0)
  report_qweb_field_option/i18n/it.po
Labels: 16.0
